# Action Cable uses Redis to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  url: redis://<%= "#{Settings.redis.cable.host}:#{Settings.redis.cable.port}/#{Settings.redis.cable.db}" %>

development:
  url: redis://<%= "#{Settings.redis.cable.host}:#{Settings.redis.cable.port}/#{Settings.redis.cable.db}" %>

test:
  url: redis://<%= "#{Settings.redis.cable.host}:#{Settings.redis.cable.port}/#{Settings.redis.cable.db}" %>
